baseURL = "http://kunugirasuku.net/"
languageCode = "ja"
title = "kunugi's room"
theme = "kunugi_room"
hasCJKLanguage = true

[markup.goldmark.renderer]
unsafe = true

[params]
twitterID = "@kunugi_rasuku"
description = "このサイトはくぬぎが適当に書いたり,作ったものを貼ったりする予定の場所です。基本的にはHugoの勉強とHTML,CSSを思い出すために作ったものなのでクオリティには触れないでもらえると助かります。。"
images = ["images/kunugirasuku_icon.png"]
mainSections = ["blog", "works"]